services:
  web:
    build:
      context: ./app/
    container_name: simple_sso_idp
    env_file:
      - .env
    
    volumes:
      - database:/app/database
      - images:/root/userimages
    ports:
      -  "${PORT:-8080}:${PORT:-8080}"
    depends_on:
      mysqldb:
        condition: service_healthy
  mysqldb:
    image: mysql:5.7
    restart: always
    expose:
      - 3306
    env_file:
      - .env
    volumes:
        - mysqldatabase:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  database:
  images:
  mysqldatabase:


